import Foundation

struct Schemata {
    private static var cache: [String: [String: Any]] = [:]

    static let registry: [String: String] = [
        "kind0ContentSchema": "Resources/nips/nip-01/kind-0/schema.content.json",
        "kind0Schema": "Resources/nips/nip-01/kind-0/schema.json",
        "kind1Schema": "Resources/nips/nip-01/kind-1/schema.json",
        "clientCloseSchema": "Resources/nips/nip-01/messages/client-close/schema.json",
        "clientEventSchema": "Resources/nips/nip-01/messages/client-event/schema.json",
        "clientReqSchema": "Resources/nips/nip-01/messages/client-req/schema.json",
        "filterSchema": "Resources/nips/nip-01/messages/filter/schema.json",
        "relayClosedSchema": "Resources/nips/nip-01/messages/relay-closed/schema.json",
        "relayEoseSchema": "Resources/nips/nip-01/messages/relay-eose/schema.json",
        "relayEventSchema": "Resources/nips/nip-01/messages/relay-event/schema.json",
        "relayNoticeSchema": "Resources/nips/nip-01/messages/relay-notice/schema.json",
        "relayOkSchema": "Resources/nips/nip-01/messages/relay-ok/schema.json",
        "noteSchema": "Resources/nips/nip-01/note/schema.json",
        "noteUnsignedSchema": "Resources/nips/nip-01/note-unsigned/schema.json",
        "secp256k1Schema": "Resources/nips/nip-01/secp256k1/schema.json",
        "aTagSchema": "Resources/nips/nip-01/tag/a/schema.json",
        "dTagSchema": "Resources/nips/nip-01/tag/d/schema.json",
        "eTagSchema": "Resources/nips/nip-01/tag/e/schema.json",
        "pTagSchema": "Resources/nips/nip-01/tag/p/schema.json",
        "tagSchema": "Resources/nips/nip-01/tag/schema.json",
        "tTagSchema": "Resources/nips/nip-01/tag/t/schema.json",
        "kind3ContentSchema": "Resources/nips/nip-02/kind-3/schema.content.json",
        "kind3Schema": "Resources/nips/nip-02/kind-3/schema.json",
        "kind4Schema": "Resources/nips/nip-04/kind-4/schema.json",
        "identifierSchema": "Resources/nips/nip-05/identifier/schema.json",
        "wellKnownSchema": "Resources/nips/nip-05/well-known/schema.json",
        "kind5Schema": "Resources/nips/nip-09/kind-5/schema.json",
        "nip11Schema": "Resources/nips/nip-11/schema.json",
        "kind10050Schema": "Resources/nips/nip-17/kind-10050/schema.json",
        "kind14Schema": "Resources/nips/nip-17/kind-14/schema.json",
        "kind15Schema": "Resources/nips/nip-17/kind-15/schema.json",
        "blurhashTagSchema": "Resources/nips/nip-17/tag/blurhash/schema.json",
        "decryptionkeyTagSchema": "Resources/nips/nip-17/tag/decryption-key/schema.json",
        "decryptionnonceTagSchema": "Resources/nips/nip-17/tag/decryption-nonce/schema.json",
        "dimTagSchema": "Resources/nips/nip-17/tag/dim/schema.json",
        "encryptionalgorithmTagSchema": "Resources/nips/nip-17/tag/encryption-algorithm/schema.json",
        "fallbackTagSchema": "Resources/nips/nip-17/tag/fallback/schema.json",
        "filetypeTagSchema": "Resources/nips/nip-17/tag/file-type/schema.json",
        "oxTagSchema": "Resources/nips/nip-17/tag/ox/schema.json",
        "relayTagSchema": "Resources/nips/nip-17/tag/relay/schema.json",
        "sizeTagSchema": "Resources/nips/nip-17/tag/size/schema.json",
        "subjectTagSchema": "Resources/nips/nip-17/tag/subject/schema.json",
        "thumbTagSchema": "Resources/nips/nip-17/tag/thumb/schema.json",
        "xTagSchema": "Resources/nips/nip-17/tag/x/schema.json",
        "kind16Schema": "Resources/nips/nip-18/kind-16/schema.json",
        "kind6Schema": "Resources/nips/nip-18/kind-6/schema.json",
        "kTagSchema": "Resources/nips/nip-18/tag/k/schema.json",
        "qTagSchema": "Resources/nips/nip-18/tag/q/schema.json",
        "kind1111Schema": "Resources/nips/nip-22/kind-1111/schema.json",
        "ATagSchema": "Resources/nips/nip-22/tag/_A/schema.json",
        "ETagSchema": "Resources/nips/nip-22/tag/_E/schema.json",
        "KTagSchema": "Resources/nips/nip-22/tag/_K/schema.json",
        "PTagSchema": "Resources/nips/nip-22/tag/_P/schema.json",
        "kind30023Schema": "Resources/nips/nip-23/kind-30023/schema.json",
        "kind30024Schema": "Resources/nips/nip-23/kind-30024/schema.json",
        "publishedatTagSchema": "Resources/nips/nip-23/tag/published_at/schema.json",
        "kind17Schema": "Resources/nips/nip-25/kind-17/schema.json",
        "kind7Schema": "Resources/nips/nip-25/kind-7/schema.json",
        "ereactTagSchema": "Resources/nips/nip-25/tag/e-react/schema.json",
        "emojiTagSchema": "Resources/nips/nip-25/tag/emoji/schema.json",
        "kind1985Schema": "Resources/nips/nip-32/kind-1985/schema.json",
        "LTagSchema": "Resources/nips/nip-32/tag/L/schema.json",
        "lTagSchema": "Resources/nips/nip-32/tag/l/schema.json",
        "kind1617Schema": "Resources/nips/nip-34/kind-1617/schema.json",
        "kind1621Schema": "Resources/nips/nip-34/kind-1621/schema.json",
        "kind1630Schema": "Resources/nips/nip-34/kind-1630/schema.json",
        "kind1631Schema": "Resources/nips/nip-34/kind-1631/schema.json",
        "kind1632Schema": "Resources/nips/nip-34/kind-1632/schema.json",
        "kind1633Schema": "Resources/nips/nip-34/kind-1633/schema.json",
        "kind30617Schema": "Resources/nips/nip-34/kind-30617/schema.json",
        "kind30618Schema": "Resources/nips/nip-34/kind-30618/schema.json",
        "appliedascommitsTagSchema": "Resources/nips/nip-34/tag/applied-as-commits/schema.json",
        "cloneTagSchema": "Resources/nips/nip-34/tag/clone/schema.json",
        "commitTagSchema": "Resources/nips/nip-34/tag/commit/schema.json",
        "commitpgpsigTagSchema": "Resources/nips/nip-34/tag/commit-pgp-sig/schema.json",
        "committerTagSchema": "Resources/nips/nip-34/tag/committer/schema.json",
        "erootTagSchema": "Resources/nips/nip-34/tag/e-root/schema.json",
        "estatusreplyTagSchema": "Resources/nips/nip-34/tag/e-status-reply/schema.json",
        "headTagSchema": "Resources/nips/nip-34/tag/head/schema.json",
        "maintainersTagSchema": "Resources/nips/nip-34/tag/maintainers/schema.json",
        "mergecommitTagSchema": "Resources/nips/nip-34/tag/merge-commit/schema.json",
        "nameTagSchema": "Resources/nips/nip-34/tag/name/schema.json",
        "parentcommitTagSchema": "Resources/nips/nip-34/tag/parent-commit/schema.json",
        "reucTagSchema": "Resources/nips/nip-34/tag/r-euc/schema.json",
        "refTagSchema": "Resources/nips/nip-34/tag/ref/schema.json",
        "webTagSchema": "Resources/nips/nip-34/tag/web/schema.json",
        "contentwarningTagSchema": "Resources/nips/nip-36/tag/content-warning/schema.json",
        "kind30315Schema": "Resources/nips/nip-38/kind-30315/schema.json",
        "expirationTagSchema": "Resources/nips/nip-38/tag/expiration/schema.json",
        "statustypeTagSchema": "Resources/nips/nip-38/tag/status-type/schema.json",
        "clientAuthSchema": "Resources/nips/nip-40/messages/client-auth/schema.json",
        "relayAuthSchema": "Resources/nips/nip-40/messages/relay-auth/schema.json",
        "kind22242Schema": "Resources/nips/nip-42/kind-22242/schema.json",
        "challengeTagSchema": "Resources/nips/nip-42/tag/challenge/schema.json",
        "kind31922Schema": "Resources/nips/nip-52/kind-31922/schema.json",
        "kind31923Schema": "Resources/nips/nip-52/kind-31923/schema.json",
        "kind31924Schema": "Resources/nips/nip-52/kind-31924/schema.json",
        "kind31925Schema": "Resources/nips/nip-52/kind-31925/schema.json",
        "endtzidTagSchema": "Resources/nips/nip-52/tag/end_tzid/schema.json",
        "fbTagSchema": "Resources/nips/nip-52/tag/fb/schema.json",
        "gTagSchema": "Resources/nips/nip-52/tag/g/schema.json",
        "locationTagSchema": "Resources/nips/nip-52/tag/location/schema.json",
        "starttzidTagSchema": "Resources/nips/nip-52/tag/start_tzid/schema.json",
        "statusTagSchema": "Resources/nips/nip-52/tag/status/schema.json",
        "kind10312Schema": "Resources/nips/nip-53/kind-10312/schema.json",
        "kind1311Schema": "Resources/nips/nip-53/kind-1311/schema.json",
        "kind30311Schema": "Resources/nips/nip-53/kind-30311/schema.json",
        "kind30312Schema": "Resources/nips/nip-53/kind-30312/schema.json",
        "kind30313Schema": "Resources/nips/nip-53/kind-30313/schema.json",
        "aliveTagSchema": "Resources/nips/nip-53/tag/a-live/schema.json",
        "aroomTagSchema": "Resources/nips/nip-53/tag/a-room/schema.json",
        "currentparticipantsTagSchema": "Resources/nips/nip-53/tag/current_participants/schema.json",
        "endpointTagSchema": "Resources/nips/nip-53/tag/endpoint/schema.json",
        "endsTagSchema": "Resources/nips/nip-53/tag/ends/schema.json",
        "handTagSchema": "Resources/nips/nip-53/tag/hand/schema.json",
        "imageTagSchema": "Resources/nips/nip-53/tag/image/schema.json",
        "pinnedTagSchema": "Resources/nips/nip-53/tag/pinned/schema.json",
        "recordingTagSchema": "Resources/nips/nip-53/tag/recording/schema.json",
        "relaysTagSchema": "Resources/nips/nip-53/tag/relays/schema.json",
        "roomTagSchema": "Resources/nips/nip-53/tag/room/schema.json",
        "serviceTagSchema": "Resources/nips/nip-53/tag/service/schema.json",
        "startsTagSchema": "Resources/nips/nip-53/tag/starts/schema.json",
        "statusliveTagSchema": "Resources/nips/nip-53/tag/status-live/schema.json",
        "statusroomTagSchema": "Resources/nips/nip-53/tag/status-room/schema.json",
        "streamingTagSchema": "Resources/nips/nip-53/tag/streaming/schema.json",
        "summaryTagSchema": "Resources/nips/nip-53/tag/summary/schema.json",
        "titleTagSchema": "Resources/nips/nip-53/tag/title/schema.json",
        "totalparticipantsTagSchema": "Resources/nips/nip-53/tag/total_participants/schema.json",
        "kind1984Schema": "Resources/nips/nip-56/kind-1984/schema.json",
        "serverTagSchema": "Resources/nips/nip-56/tag/server/schema.json",
        "kind9734Schema": "Resources/nips/nip-57/kind-9734/schema.json",
        "kind9735Schema": "Resources/nips/nip-57/kind-9735/schema.json",
        "amountTagSchema": "Resources/nips/nip-57/tag/amount/schema.json",
        "bolt11TagSchema": "Resources/nips/nip-57/tag/bolt11/schema.json",
        "descriptionTagSchema": "Resources/nips/nip-57/tag/description/schema.json",
        "lnurlTagSchema": "Resources/nips/nip-57/tag/lnurl/schema.json",
        "preimageTagSchema": "Resources/nips/nip-57/tag/preimage/schema.json",
        "kind1059Schema": "Resources/nips/nip-59/kind-1059/schema.json",
        "kind13Schema": "Resources/nips/nip-59/kind-13/schema.json",
        "kind10019Schema": "Resources/nips/nip-61/kind-10019/schema.json",
        "kind7376Schema": "Resources/nips/nip-61/kind-7376/schema.json",
        "kind9321Schema": "Resources/nips/nip-61/kind-9321/schema.json",
        "eredeemedTagSchema": "Resources/nips/nip-61/tag/e-redeemed/schema.json",
        "mintTagSchema": "Resources/nips/nip-61/tag/mint/schema.json",
        "proofTagSchema": "Resources/nips/nip-61/tag/proof/schema.json",
        "pubkeyTagSchema": "Resources/nips/nip-61/tag/pubkey/schema.json",
        "uTagSchema": "Resources/nips/nip-61/tag/u/schema.json",
        "kind10002Schema": "Resources/nips/nip-65/kind-10002/schema.json",
        "rTagSchema": "Resources/nips/nip-65/tag/r/schema.json",
        "kind20Schema": "Resources/nips/nip-68/kind-20/schema.json",
        "imetaTagSchema": "Resources/nips/nip-68/tag/imeta/schema.json",
        "iTagSchema": "Resources/nips/nip-73/tag/i/schema.json",
        "kind30078Schema": "Resources/nips/nip-78/kind-30078/schema.json",
        "kind9802Schema": "Resources/nips/nip-84/kind-9802/schema.json",
        "commentTagSchema": "Resources/nips/nip-84/tag/comment/schema.json",
        "contextTagSchema": "Resources/nips/nip-84/tag/context/schema.json",
        "kind1018Schema": "Resources/nips/nip-88/kind-1018/schema.json",
        "kind1068Schema": "Resources/nips/nip-88/kind-1068/schema.json",
        "endsAtTagSchema": "Resources/nips/nip-88/tag/endsAt/schema.json",
        "optionTagSchema": "Resources/nips/nip-88/tag/option/schema.json",
        "polltypeTagSchema": "Resources/nips/nip-88/tag/polltype/schema.json",
        "responseTagSchema": "Resources/nips/nip-88/tag/response/schema.json",
        "kind31989Schema": "Resources/nips/nip-89/kind-31989/schema.json",
        "kind31990Schema": "Resources/nips/nip-89/kind-31990/schema.json",
        "clientTagSchema": "Resources/nips/nip-89/tag/client/schema.json",
        "kind30402Schema": "Resources/nips/nip-99/kind-30402/schema.json",
        "kind30403Schema": "Resources/nips/nip-99/kind-30403/schema.json",
        "kind10063Schema": "Resources/nips/nip-b7/kind-10063/schema.json",
        "kind10051Schema": "Resources/mips/mip-00/kind-10051/schema.json",
        "kind443Schema": "Resources/mips/mip-00/kind-443/schema.json",
        "encodingTagSchema": "Resources/mips/mip-00/tag/encoding/schema.json",
        "mlsciphersuiteTagSchema": "Resources/mips/mip-00/tag/mls_ciphersuite/schema.json",
        "mlsextensionsTagSchema": "Resources/mips/mip-00/tag/mls_extensions/schema.json",
        "mlsprotocolversionTagSchema": "Resources/mips/mip-00/tag/mls_protocol_version/schema.json",
        "kind444Schema": "Resources/mips/mip-02/kind-444/schema.json",
        "kind445Schema": "Resources/mips/mip-03/kind-445/schema.json",
        "hTagSchema": "Resources/mips/mip-03/tag/h/schema.json",
        "messagefilterSchema": "Resources/_aliases/message/filter.json",
        "nip05Schema": "Resources/_aliases/nip05.json",
        "nostrwellknownSchema": "Resources/_aliases/nostr-well-known.json",
        "notekind22242Schema": "Resources/_aliases/note/kind-22242.json",
        "noteunsignedSchema": "Resources/_aliases/note-unsigned.json",
        "authrelayTagSchema": "Resources/_aliases/tag/auth-relay.json",
        "dmrelayTagSchema": "Resources/_aliases/tag/dm-relay.json",
        "externalcontentiTagSchema": "Resources/_aliases/tag/external-content-i.json",
        "externalcontentkTagSchema": "Resources/_aliases/tag/external-content-k.json",
        "gitrefTagSchema": "Resources/_aliases/tag/git-ref.json",
        "mip00iTagSchema": "Resources/_aliases/tag/mip-00_i.json",
        "mlsclientTagSchema": "Resources/_aliases/tag/mls_client.json",
        "reactioneTagSchema": "Resources/_aliases/tag/reaction-e.json",
    ]

    /// Returns parsed JSON schema for the given key, or nil.
    static func get(_ key: String) -> [String: Any]? {
        if let cached = cache[key] {
            return cached
        }
        guard let relativePath = registry[key] else { return nil }

        let pathComponents = relativePath.split(separator: "/")
        let filename = String(pathComponents.last!).replacingOccurrences(of: ".json", with: "")
        let subdir = pathComponents.dropLast().joined(separator: "/")

        guard let url = Bundle.module.url(forResource: filename, withExtension: "json", subdirectory: subdir) else {
            return nil
        }
        guard let data = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }
        cache[key] = json
        return json
    }

    /// Returns all available schema registry keys.
    static func keys() -> [String] {
        return registry.keys.sorted()
    }
}
